import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const patch = await readFile(new URL("../integration-packages/growth-partner-pwa/supabase-integration.patch", import.meta.url), "utf8");
const migration = await readFile(new URL("../supabase/migrations/20260806_growth_partner_identity.sql", import.meta.url), "utf8");
const readme = await readFile(new URL("../integration-packages/growth-partner-pwa/README.md", import.meta.url), "utf8");
const added = patch.split("\n").filter((line) => line.startsWith("+") && !line.startsWith("+++" )).join("\n");

test("Phase 3 patch targets the current locked Growth Partner main", () => {
  assert.match(readme, /2832af2/);
  assert.match(patch, /src\/lib\/gpRepository\.ts/);
  assert.match(patch, /src\/components\/AddShop\.tsx/);
  assert.match(patch, /VITE_APP_BASE_PATH/);
});

test("Growth Partner auth is real, permanent-role gated, and env-only", () => {
  assert.match(patch, /supabase\.auth\.signInWithPassword|isGrowthPartnerRole/);
  assert.match(patch, /profiles/);
  assert.match(patch, /platform_role/);
  assert.match(patch, /growth_partner/);
  assert.doesNotMatch(added, /isAuthenticated/);
  assert.doesNotMatch(added, /DEFAULT_PARTNER_PROFILE|DEFAULT_DASHBOARD_CACHE/);
  assert.doesNotMatch(added, /eyJhbGciOiJIUzI1Ni/);
  assert.match(patch, /VITE_SUPABASE_URL/);
  assert.match(patch, /VITE_SUPABASE_ANON_KEY/);
});

test("referral identity is generated by a server RPC", () => {
  assert.match(migration, /ensure_growth_partner_identity/);
  assert.match(migration, /profile_role is distinct from 'growth_partner'/);
  assert.match(migration, /generated_code/);
  assert.match(migration, /generated_referral/);
  assert.match(migration, /grant execute on function public\.ensure_growth_partner_identity\(\) to authenticated/);
  assert.match(added, /rpc\('ensure_growth_partner_identity'\)/);
  assert.match(added, /referral_code/);
});

test("proposal submission uses the existing server-owned contracts", () => {
  assert.match(added, /shop_onboarding_applications/);
  assert.match(added, /submitted_by_partner_id/);
  assert.match(added, /rpc\('save_growth_partner_salon_setup'/);
  assert.match(added, /p_submit: true/);
  assert.doesNotMatch(added, /alert\([^\n]*submitted successfully/);
});

test("attribution and commission views are live and read-only", () => {
  assert.match(patch, /shop_attributions/);
  assert.match(patch, /growth_partner_commissions/);
  assert.match(patch, /heldPaise/);
  assert.match(patch, /payablePaise/);
  assert.match(patch, /paidPaise/);
  assert.match(patch, /No attributed shops yet/);
  assert.match(added, /No local account registry|server-owned/);
});

test("Growth Partner worker and raw-origin mount stay scoped", () => {
  assert.match(patch, /serviceWorker\.register/);
  assert.match(patch, /scope: portalBase/);
  assert.match(patch, /VITE_CANONICAL_ORIGIN/);
  assert.match(patch, /Service-Worker-Allowed/);
  assert.match(patch, /\/app\/partner\//);
});
