import { createContext, useContext } from 'react';
import type { Dispatch, RefObject, SetStateAction } from 'react';
import type { SalonData, Service, Package } from '../../types';
import type { ThemeId } from '../../lib/themeServices';
import type { SiteHeaderThemeId } from '../../lib/siteNavigation';
import type { BrandConfig } from '../../config/brandConfig';
import type { BookingActorContext } from '../../lib/bookingManagement';
import type { WeeklyTopVideo } from '../../lib/videoLikes';
import { useSiteLocale } from '../../components/SiteHeader';
import { videoGalleryChrome } from '../../lib/siteVideoGalleryI18n';
import type { Appointment, DashboardNotification, DashboardTab } from './types';
import type React from 'react';

/**
 * Shared dashboard state contract. DashboardScreen owns every piece of state
 * (the declarations moved verbatim from the old Landing.tsx monolith) and
 * exposes it through this context; each lazy tab consumes only what it needs.
 */
export interface DashboardContextValue {
  data: SalonData;
  setData: Dispatch<SetStateAction<SalonData>>;
  goToStep: (target: number) => void;
  onOpenStaffManagement: () => void;
  activeTab: DashboardTab;
  setActiveTab: (tab: DashboardTab) => void;
  onThemeChange: ((id: ThemeId) => void) | undefined;
  platform: BrandConfig['platform'];
  defaultSalon: BrandConfig['defaultSalon'];
  liveSlug: string;
  liveUrl: string;
  currentThemeId: SiteHeaderThemeId;
  locale: ReturnType<typeof useSiteLocale>;
  chrome: ReturnType<typeof videoGalleryChrome>;
  dashboardWeeklyTop: WeeklyTopVideo[];
  totalBookingsValue: number;
  totalAdvanceCollected: number;
  totalRemainingAtSalon: number;
  activeServicesCount: number;
  staffTeamCount: number;
  todayActiveBookings: number;
  mode: 'desktop' | 'mobile';
  setMode: Dispatch<SetStateAction<'desktop' | 'mobile'>>;
  copied: boolean;
  handleCopyLink: () => void;
  appointments: Appointment[];
  setAppointments: Dispatch<SetStateAction<Appointment[]>>;
  handleUpdateApptStatus: (apptId: string, nextStatus: Appointment['status']) => void;
  handleDeleteAppt: (apptId: string) => void;
  handleCreateAppointment: (e: React.FormEvent) => void;
  showNewAppointmentModal: boolean;
  setShowNewAppointmentModal: Dispatch<SetStateAction<boolean>>;
  handleToggleStaffStatus: (id: string) => void;
  notifications: DashboardNotification[];
  setShowNotifications: Dispatch<SetStateAction<boolean>>;
  setNotifications: Dispatch<SetStateAction<DashboardNotification[]>>;
  showNotifications: boolean;
  updateTagline: (tagline: string) => void;
  taglineOptions: string[];
  taglineCategory: string;
  setTaglineCategory: Dispatch<SetStateAction<string>>;
  taglineSubcategory: string;
  setTaglineSubcategory: Dispatch<SetStateAction<string>>;
  handlePolishText: (field: 'tagline' | 'about' | 'bio', tone: 'luxury' | 'modern' | 'warm') => void;
  polishingField: 'tagline' | 'about' | 'bio' | null;
  setPolishingField: Dispatch<SetStateAction<'tagline' | 'about' | 'bio' | null>>;
  polishingStatus: string;
  setPolishingStatus: Dispatch<SetStateAction<string>>;
  ownerPhotoInputRef: RefObject<HTMLInputElement | null>;
  ownerPhotoError: string | null;
  setOwnerPhotoError: Dispatch<SetStateAction<string | null>>;
  ownerPhotoBusy: boolean;
  setOwnerPhotoBusy: Dispatch<SetStateAction<boolean>>;
  handleOwnerPhotoFile: (file: File | undefined) => Promise<void>;
  handleRemoveOwnerPhoto: () => void;
  showHelpCenter: boolean;
  setShowHelpCenter: Dispatch<SetStateAction<boolean>>;
  showLiveSiteModal: boolean;
  setShowLiveSiteModal: Dispatch<SetStateAction<boolean>>;
  servicesSubTab: 'services' | 'packages';
  setServicesSubTab: Dispatch<SetStateAction<'services' | 'packages'>>;
  servicesSearchQuery: string;
  setServicesSearchQuery: Dispatch<SetStateAction<string>>;
  servicesSelectedCategory: string;
  setServicesSelectedCategory: Dispatch<SetStateAction<string>>;
  servicesViewLayout: 'list' | 'grid';
  setServicesViewLayout: Dispatch<SetStateAction<'list' | 'grid'>>;
  editingService: Service | null;
  setEditingService: Dispatch<SetStateAction<Service | null>>;
  editingPackage: Package | null;
  setEditingPackage: Dispatch<SetStateAction<Package | null>>;
  showServiceDrawer: boolean;
  setShowServiceDrawer: Dispatch<SetStateAction<boolean>>;
  showPackageDrawer: boolean;
  setShowPackageDrawer: Dispatch<SetStateAction<boolean>>;
  isImprovingWithAI: boolean;
  setIsImprovingWithAI: Dispatch<SetStateAction<boolean>>;
  newServiceName: string;
  setNewServiceName: Dispatch<SetStateAction<string>>;
  newServiceCategory: string;
  setNewServiceCategory: Dispatch<SetStateAction<string>>;
  newServicePrice: number;
  setNewServicePrice: Dispatch<SetStateAction<number>>;
  newServiceDuration: number;
  setNewServiceDuration: Dispatch<SetStateAction<number>>;
  newServiceDesc: string;
  setNewServiceDesc: Dispatch<SetStateAction<string>>;
  newServiceFeatured: boolean;
  setNewServiceFeatured: Dispatch<SetStateAction<boolean>>;
  newPackageName: string;
  setNewPackageName: Dispatch<SetStateAction<string>>;
  newPackagePrice: number;
  setNewPackagePrice: Dispatch<SetStateAction<number>>;
  newPackageDuration: number;
  setNewPackageDuration: Dispatch<SetStateAction<number>>;
  newPackageDesc: string;
  setNewPackageDesc: Dispatch<SetStateAction<string>>;
  handleSaveService: (e: React.FormEvent) => void;
  handleDuplicateService: (serv: Service) => void;
  handleDeleteService: (id: string, name: string) => void;
  handleSavePackage: (e: React.FormEvent) => void;
  handleDuplicatePackage: (pkg: Package) => void;
  handleDeletePackage: (id: string, name: string) => void;
  handleImproveDescriptionWithAI: () => void;
  handleImprovePackageDescWithAI: () => void;
  showVoiceModal: boolean;
  setShowVoiceModal: Dispatch<SetStateAction<boolean>>;
  voiceInputText: string;
  setVoiceInputText: Dispatch<SetStateAction<string>>;
  isVoiceListening: boolean;
  setIsVoiceListening: Dispatch<SetStateAction<boolean>>;
  handleParseVoiceCommand: () => void;
  showAiSuggestModal: boolean;
  setShowAiSuggestModal: Dispatch<SetStateAction<boolean>>;
  aiSuggestArchetype: 'luxury' | 'barber' | 'spa' | 'beauty';
  setAiSuggestArchetype: Dispatch<SetStateAction<'luxury' | 'barber' | 'spa' | 'beauty'>>;
  isGeneratingSuggestions: boolean;
  setIsGeneratingSuggestions: Dispatch<SetStateAction<boolean>>;
  generatedSuggestions: Service[];
  setGeneratedSuggestions: Dispatch<SetStateAction<Service[]>>;
  selectedSuggestionIds: string[];
  setSelectedSuggestionIds: Dispatch<SetStateAction<string[]>>;
  handleTriggerSuggestions: (archetype: 'luxury' | 'barber' | 'spa' | 'beauty') => void;
  handleAddSuggestionsToCatalog: () => void;
  newCustName: string;
  setNewCustName: Dispatch<SetStateAction<string>>;
  newCustPhone: string;
  setNewCustPhone: Dispatch<SetStateAction<string>>;
  newSelectedService: string;
  setNewSelectedService: Dispatch<SetStateAction<string>>;
  newSelectedStaff: string;
  setNewSelectedStaff: Dispatch<SetStateAction<string>>;
  newSelectedTime: string;
  setNewSelectedTime: Dispatch<SetStateAction<string>>;
  bookingActor: BookingActorContext;
  bookingTenantId: string;
  bookingToast: string | null;
  setBookingToast: Dispatch<SetStateAction<string | null>>;
  paymentsFilter: 'All'|'Verified'|'Pending'|'Failed'|'Refunded';
  setPaymentsFilter: Dispatch<SetStateAction<'All'|'Verified'|'Pending'|'Failed'|'Refunded'>>;
  paymentsSearch: string;
  setPaymentsSearch: Dispatch<SetStateAction<string>>;
  selectedPaymentId: string;
  setSelectedPaymentId: Dispatch<SetStateAction<string>>;
}

export const DashboardContext = createContext<DashboardContextValue | null>(null);

export function useDashboard(): DashboardContextValue {
  const ctx = useContext(DashboardContext);
  if (!ctx) throw new Error('useDashboard must be used inside <DashboardContext.Provider>');
  return ctx;
}
